/* Generated by Yosys 0.32+51 (git sha1 6405bbab1, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module pes_elevator(request_floor, in_current_floor, clk, reset, complete, direction, over_time, over_weight, weight_alert, door_alert, out_current_floor);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  input clk;
  wire clk;
  output complete;
  wire complete;
  output direction;
  wire direction;
  output door_alert;
  wire door_alert;
  input [7:0] in_current_floor;
  wire [7:0] in_current_floor;
  output [7:0] out_current_floor;
  wire [7:0] out_current_floor;
  input over_time;
  wire over_time;
  input over_weight;
  wire over_weight;
  reg r_complete;
  reg r_direction;
  reg r_door_alert;
  reg [7:0] r_out_current_floor;
  reg r_weight_alert;
  input [7:0] request_floor;
  wire [7:0] request_floor;
  input reset;
  wire reset;
  output weight_alert;
  wire weight_alert;
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(_138_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _152_ (
    .A(_137_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(_135_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2b_1 _154_ (
    .A_N(_141_),
    .B(_149_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(_141_),
    .B(_149_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _156_ (
    .A(_140_),
    .B(_148_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__and2_0 _157_ (
    .A(_092_),
    .B(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__nor2b_1 _158_ (
    .A(_139_),
    .B_N(_147_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_1 _159_ (
    .A(_139_),
    .B(_147_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _160_ (
    .A(_146_),
    .B(_138_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and3_1 _161_ (
    .A(_094_),
    .B(_096_),
    .C(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _162_ (
    .A(_094_),
    .B(_096_),
    .C(_097_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__xor2_1 _163_ (
    .A(_137_),
    .B(_145_),
    .X(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _164_ (
    .A(_136_),
    .B(_144_),
    .X(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2b_1 _166_ (
    .A(_134_),
    .B_N(_142_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor3_1 _167_ (
    .A(_100_),
    .B(_101_),
    .C(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2b_1 _168_ (
    .A_N(_142_),
    .B(_134_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _169_ (
    .A(_135_),
    .B(_143_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand4_1 _170_ (
    .A(_098_),
    .B(_104_),
    .C(_105_),
    .D(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__clkinv_1 _171_ (
    .A(_107_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor3_1 _172_ (
    .A(_132_),
    .B(_150_),
    .C(_133_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_071_),
    .B(_108_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__or2_0 _174_ (
    .A(_150_),
    .B(_108_),
    .X(_067_)
  );
  sky130_fd_sc_hd__and2_0 _175_ (
    .A(_068_),
    .B(_067_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2b_1 _176_ (
    .A(_150_),
    .B_N(_132_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__or3_1 _177_ (
    .A(_132_),
    .B(_150_),
    .C(_108_),
    .X(_070_)
  );
  sky130_fd_sc_hd__nor2b_1 _178_ (
    .A(_150_),
    .B_N(_133_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(_150_),
    .B(_075_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__maj3_1 _180_ (
    .A(_090_),
    .B(_143_),
    .C(_105_),
    .X(_110_)
  );
  sky130_fd_sc_hd__nor3b_1 _181_ (
    .A(_100_),
    .B(_136_),
    .C_N(_144_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a221oi_1 _182_ (
    .A1(_089_),
    .A2(_145_),
    .B1(_102_),
    .B2(_110_),
    .C1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a31o_1 _183_ (
    .A1(_146_),
    .A2(_088_),
    .A3(_096_),
    .B1(_095_),
    .X(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(_094_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3b_1 _185_ (
    .A_N(_140_),
    .B(_148_),
    .C(_092_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o2111a_1 _186_ (
    .A1(_099_),
    .A2(_112_),
    .B1(_114_),
    .C1(_115_),
    .D1(_091_),
    .X(_116_)
  );
  sky130_fd_sc_hd__o2111ai_1 _187_ (
    .A1(_099_),
    .A2(_112_),
    .B1(_114_),
    .C1(_115_),
    .D1(_091_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _188_ (
    .A(_071_),
    .B(_116_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o31ai_1 _189_ (
    .A1(_150_),
    .A2(_090_),
    .A3(_118_),
    .B1(_109_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(_150_),
    .B(_076_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _191_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_136_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor3_1 _192_ (
    .A(_134_),
    .B(_071_),
    .C(_116_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o31ai_1 _193_ (
    .A1(_150_),
    .A2(_120_),
    .A3(_121_),
    .B1(_119_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _194_ (
    .A1(_071_),
    .A2(_116_),
    .B1(_089_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a31oi_1 _195_ (
    .A1(_090_),
    .A2(_107_),
    .A3(_117_),
    .B1(_150_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a22o_1 _196_ (
    .A1(_150_),
    .A2(_077_),
    .B1(_122_),
    .B2(_123_),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(_150_),
    .B(_078_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a21oi_1 _198_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_138_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor3_1 _199_ (
    .A(_136_),
    .B(_071_),
    .C(_116_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o31ai_1 _200_ (
    .A1(_150_),
    .A2(_125_),
    .A3(_126_),
    .B1(_124_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(_150_),
    .B(_079_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a21oi_1 _202_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_139_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor3_1 _203_ (
    .A(_137_),
    .B(_071_),
    .C(_116_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o31ai_1 _204_ (
    .A1(_150_),
    .A2(_128_),
    .A3(_129_),
    .B1(_127_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(_150_),
    .B(_080_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a21oi_1 _206_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_140_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor3_1 _207_ (
    .A(_138_),
    .B(_071_),
    .C(_116_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o31ai_1 _208_ (
    .A1(_150_),
    .A2(_131_),
    .A3(_083_),
    .B1(_130_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_150_),
    .B(_081_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a21oi_1 _210_ (
    .A1(_107_),
    .A2(_117_),
    .B1(_141_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor3_1 _211_ (
    .A(_139_),
    .B(_071_),
    .C(_116_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o31ai_1 _212_ (
    .A1(_150_),
    .A2(_085_),
    .A3(_086_),
    .B1(_084_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2b_1 _213_ (
    .A(_150_),
    .B_N(_140_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a22o_1 _214_ (
    .A1(_150_),
    .A2(_082_),
    .B1(_118_),
    .B2(_087_),
    .X(_066_)
  );
  sky130_fd_sc_hd__a21o_1 _215_ (
    .A1(_108_),
    .A2(_118_),
    .B1(_150_),
    .X(_074_)
  );
  always @(posedge clk)
    if (_003_) r_out_current_floor[0] <= _000_[0];
  always @(posedge clk)
    if (_003_) r_out_current_floor[1] <= _000_[1];
  always @(posedge clk)
    if (_003_) r_out_current_floor[2] <= _000_[2];
  always @(posedge clk)
    if (_003_) r_out_current_floor[3] <= _000_[3];
  always @(posedge clk)
    if (_003_) r_out_current_floor[4] <= _000_[4];
  always @(posedge clk)
    if (_003_) r_out_current_floor[5] <= _000_[5];
  always @(posedge clk)
    if (_003_) r_out_current_floor[6] <= _000_[6];
  always @(posedge clk)
    if (_003_) r_out_current_floor[7] <= _000_[7];
  always @(posedge clk)
    if (reset) r_direction <= 1'h1;
    else r_direction <= _058_;
  always @(posedge clk)
    if (_002_) r_complete <= 1'h0;
    else r_complete <= _005_;
  always @(posedge clk)
    if (_001_) r_door_alert <= 1'h0;
    else r_door_alert <= _006_;
  always @(posedge clk)
    if (_004_) r_weight_alert <= 1'h0;
    else r_weight_alert <= _007_;
  assign complete = r_complete;
  assign direction = r_direction;
  assign door_alert = r_door_alert;
  assign out_current_floor = r_out_current_floor;
  assign weight_alert = r_weight_alert;
  assign _132_ = over_time;
  assign _150_ = reset;
  assign _133_ = over_weight;
  assign _141_ = r_out_current_floor[7];
  assign _149_ = request_floor[7];
  assign _140_ = r_out_current_floor[6];
  assign _148_ = request_floor[6];
  assign _139_ = r_out_current_floor[5];
  assign _147_ = request_floor[5];
  assign _146_ = request_floor[4];
  assign _138_ = r_out_current_floor[4];
  assign _137_ = r_out_current_floor[3];
  assign _145_ = request_floor[3];
  assign _136_ = r_out_current_floor[2];
  assign _144_ = request_floor[2];
  assign _135_ = r_out_current_floor[1];
  assign _143_ = request_floor[1];
  assign _142_ = request_floor[0];
  assign _134_ = r_out_current_floor[0];
  assign _005_ = _071_;
  assign _002_ = _068_;
  assign _001_ = _067_;
  assign _003_ = _069_;
  assign _006_ = _072_;
  assign _004_ = _070_;
  assign _007_ = _073_;
  assign _075_ = in_current_floor[0];
  assign _000_[0] = _059_;
  assign _076_ = in_current_floor[1];
  assign _000_[1] = _060_;
  assign _077_ = in_current_floor[2];
  assign _000_[2] = _061_;
  assign _078_ = in_current_floor[3];
  assign _000_[3] = _062_;
  assign _079_ = in_current_floor[4];
  assign _000_[4] = _063_;
  assign _080_ = in_current_floor[5];
  assign _000_[5] = _064_;
  assign _081_ = in_current_floor[6];
  assign _000_[6] = _065_;
  assign _082_ = in_current_floor[7];
  assign _000_[7] = _066_;
  assign _058_ = _074_;
endmodule
